### ISSUE TITLE
Activating extension 'monosans.djlint' failed: (0 , yl.getDefaultHighWaterMark) is not a function.

### ISSUE THREAD

**Issue by mousetail** [djlint/djlint-vscode#934]
After installing DJLint, it wouldn't format. I checked the inspector and got this error.

My system:

![image](https://github.com/user-attachments/assets/bd1ec74e-10c5-4c1b-aa99-21ee81c0df87)

Full error:

```
2024-10-11 16:52:28.506 [error] Activating extension monosans.djlint failed due to an error:
2024-10-11 16:52:28.507 [error] TypeError: (0 , yl.getDefaultHighWaterMark) is not a function
	at Object.<anonymous> (/home/mousetail/.vscodium-server/extensions/monosans.djlint-2024.7.0-universal/out/extension.js:42:24519)
	at Module._compile (node:internal/modules/cjs/loader:1198:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
	at Module.load (node:internal/modules/cjs/loader:1076:32)
	at Function.Module._load (node:internal/modules/cjs/loader:911:12)
	at Function.w._load (/home/mousetail/.vscodium-server/bin/21b1e2955ddda36eeba3a94e643128e465285b93/out/vs/workbench/api/node/extensionHostProcess.js:177:7371)
	at Function.i._load (/home/mousetail/.vscodium-server/bin/21b1e2955ddda36eeba3a94e643128e465285b93/out/vs/workbench/api/node/extensionHostProcess.js:174:38745)
	at Function.o._load (/home/mousetail/.vscodium-server/bin/21b1e2955ddda36eeba3a94e643128e465285b93/out/vs/workbench/api/node/extensionHostProcess.js:139:44377)
	at Module.require (node:internal/modules/cjs/loader:1100:19)
	at require (node:internal/modules/cjs/helpers:119:18)
	at Function.i [as __$__nodeRequire] (/home/mousetail/.vscodium-server/bin/21b1e2955ddda36eeba3a94e643128e465285b93/out/bootstrap-fork.js:3:98)
	at m._loadCommonJSModule (/home/mousetail/.vscodium-server/bin/21b1e2955ddda36eeba3a94e643128e465285b93/out/vs/workbench/api/node/extensionHostProcess.js:174:40372)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```

Happy to help with any further debugging steps necessary.

**Comment by monosans** [comment]
Hey, @mousetail! The issue is still present on the latest versions of VSCode and the extension?

**Comment by mousetail** [comment]
I've updated to the latest version of the extension but the problem persists. I'm a minor version behind on VsCodium because another extension isn't compatible but it should be updated within a few weeks.

**Comment by mousetail** [comment]
I updates to the latest version of both and the issue persists:
```
Version: 1.95.1
Release: 24307
Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d
Date: 2024-11-02T15:11:43.867Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

```
Activating extension 'monosans.djlint' failed: (0 , Tl.getDefaultHighWaterMark) is not a function.
```
(The message changed slightly because the minification)

**Comment by monosans** [comment]
Closing this due to inactivity. Please let me know if the issue is still present on the latest versions of VSCode and I will reopen the issue.
